### ISSUE TITLE
statusbot could PM people asking for their status

### ISSUE THREAD

**Issue by seanmonstar** [benadida/teamstatus#29] opened 2012-08-30 17:43 UTC
If statusbot were to PM everyone one or twice a day asking for their status, we might be more inclined to keep it up to date. Idea from http://blog.alexmaccaw.com/stripes-culture

I know I never actually think of telling statusbot.

**Comment by benadida** [comment] 2012-12-28 18:44
duplicate of issue #24

**Closed as completed by benadida** 2012-12-28 18:44 UTC
